export const tasks = [
  {
    id: "1",
    title: "Погулять с собакой",
    description: "Погулять с собакой минимум 30 минут",
    dayIndex: 3,
    isDone: false,
  },
  {
    id: "2",
    title: "Убраться дома",
    description: "Помыть пол и посуду",
    dayIndex: 0,
    isDone: false,
  },
  {
    id: "3",
    title: "Сделать рабочие задачи",
    description: "Задача 1, задача 2, задача 3",
    dayIndex: 2,
    isDone: false,
  },
  {
    id: "4",
    title: "Посмотреть курс",
    description: "3 урок",
    dayIndex: 3,
    isDone: false,
  },
  {
    id: "5",
    title: "Посетить пары",
    description: "По расписанию",
    dayIndex: 4,
    isDone: false,
  },
  {
    id: "6",
    title: "Погулять с собакой",
    description: "Погулять с собакой минимум 30 минут",
    dayIndex: 2,
    isDone: true,
  },
  {
    id: "7",
    title: "Убраться дома",
    description: "Помыть пол и посуду",
    dayIndex: 4,
    isDone: false,
  },
  {
    id: "8",
    title: "Сделать рабочие задачи",
    description: "Задача 1, задача 2, задача 3",
    dayIndex: 1,
    isDone: false,
  },
  {
    id: "9",
    title: "Посмотреть курс",
    description: "3 урок",
    dayIndex: 5,
    isDone: false,
  },
  {
    id: "10",
    title: "Посетить пары",
    description: "По расписанию",
    dayIndex: 6,
    isDone: false,
  },
];
